### ISSUE TITLE
استفاده از چند datepicker

### ISSUE THREAD

**Issue by mahdikazemi96** [h-rafiee/Datepicker-Jalali#3]
سلام
من میخوام داخل یک صفحه از سه تا دیت پیکر استفاده کنم اما نمیتونم میشه راهنمایی کنید ؟
ممنون

**Comment by adevneverdies** [comment]
سلام 
اولان میبخشید که دیر دارم جواب میدم
تا اونجایی که یادمه استفاده چندباره اش رو انجام دادم ولی یکسری مشکلهایی هم داشت
یا چند باره برای چندتا سلکتور خودتون صدا بزنید
یا یکبار برای یک کلاس استفاده کنید و چند بار همون کلاس رو بنویسید

```
$("#id1").datepicker({
    altField : "#calendarInput",
    date : "2015-01-02"
});
$("#id2").datepicker({
    altField : "#calendarInput-2",
    date : "2015-01-02"
});
```
